- name: Install htop
  apt: 
      name: htop
      state: present
- name: Install R
  apt: 
      name: r-base
      state: present
- name: Install pycharm
  command: snap install pycharm-community --classic
- name: Install vscode
  command: snap install vscode --classic
