- name: Install htop
  apt: 
      name: htop
      state: present
- name: Install R
  apt: 
      name: r-base
      state: present
- name: Install spyder
  apt:
      name: spyder
      state: present
- name: Install sqlite3
  apt:
      name: sqlite3
      state: present
- name: Install vscode
  command: snap install code --classic
